// client-react/src/components/Header/Header.jsx
import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Switch } from '../Switch/Switch';
import { BackArrow } from '../../assets';
import './Header.css';

export const Header = () => {
    const { pathname } = useLocation();
    const navigate = useNavigate();

    const back = () => navigate('');

    return (
        <div className='header-container'>
            {
                pathname.includes('contact') && (
                    <BackArrow
                        className='back-arrow'
                        onClick={back}
                    />
                )
            }
            <Switch />
        </div>
    );
};

// client-vue/src/layouts/Header.vue
<template>
  <div class="header-container">
    <BackArrowIcon
        v-if="$route.path.includes('contact')"
        class="back-arrow"
        @click="back"
    />
    <Switch />
  </div>
</template>

<script>
import { Switch } from '@/components';
import { BackArrowIcon } from '@/assets';

export default {
  methods: {
    back() {
      this.$router.go(-1);
    }
  },
  name: 'Header',
  components: { BackArrowIcon, Switch },
};
</script>

<style scoped>
.header-container {
  width: 100%;
  display: flex;
  position: relative;
  z-index: 1;
}

.back-arrow {
  margin-left: 1%;
  width: 3%;
  color: var(--primary-color);
}

</style>
